#!/bin/bash
####################################
# kmra.sh Author : Simon Lhoir     #
# -------------------------------- #
#                                  #
# V 1.0 20160206                   #
####################################

# on récupère les variables globales
# et les fonctions de base
. envi.sh
. fnct.sh

DHSLog BeginTask $0
